# Site settings
title: Eating sleeping wooq
email: wooq@nhnnext.org
description: > # this means to ignore newlines until "baseurl:"
  wooq's blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: summermoghi
github_username:  wooq17

# Build settings
markdown: kramdown
